### PR TITLE
Added Exponential Backoff

### LINKED ISSUE #4: Wrong API url
> Need to change back the url to the public api one 

 _Originally posted by @ValDesign22 in [46092a7](https://github.com/DiscordAnalytics/python-package/commit/46092a7dd809013214da2c338d3d2b0dc210f3b1#r148865809)_

### PR DESCRIPTION
**Pull request by JamsRepos**
This is to avoid the API or Discord having issues and causing the analytics to never recover.

### CODE REVIEW

**Review by ValDesign22 — APPROVED** [review]
Seems good to me

**Comment by ValDesign22** [comment]
The code seems good, but does it works?

**Comment by JamsRepos** [comment]
> The code seems good, but does it works?

Just tested it on my local, it works all fine. I was unable to "fake" an API error though, that bit hasn't been tested.

**Comment by ValDesign22** [comment]
okay

**Comment by JamsRepos** [comment]
If you could run the API locally and then cut it off and see what happens, that would work but I don't have the API locally to test cutting the connection.

**Comment by ValDesign22** [comment]
good idea !

**Pull request merged**
